theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "docker"
interval = 1
format = "{running}/{total}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 1

[[block]]
block = "nvidia_gpu"
label = "RTX 2070"
show_memory = true
show_clocks = true
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R"
