theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "docker"
interval = 1
format = "{running}/{total}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "memory"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 1

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R"
